# Generated by Django 4.2.7 on 2023-12-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0008_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_countries',
            field=models.ManyToManyField(related_name='books', to='book_outlet.country'),
        ),
    ]
